### ISSUE TITLE
sb deploy fails due to permission issue,

### ISSUE THREAD

**Issue by jdgh000** [microsoft/superbenchmark#531] opened 2023-05-09 16:20 UTC
**What's the issue, what's expected?**:

Seeing following during deploy. My suspicion is that when the docker storage is mounted at different linux lvm/partition than root/boot volume of linux, it seems to be happening but can not be certain. Otherwise, it is most typical setup and run.
I perceive this as superbenchmakr issue because on same configuration, other docker/containers are running just fine.  

TASK [Generating SSH Config] ***************************************************
changed: [localhost]

TASK [Generating SSH Key Pair] *************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Error while setting attributes: /home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24/id_ed25519: Invalid argument
fatal: [localhost]: FAILED! => {"changed": false, "details": "Error while setting attributes: /home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24/id_ed25519: Invalid argument\n", "gid": 0, "group": "root", "mode": "0600", "msg": "chattr failed", "owner": "root", "path": "/home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24/id_ed25519", "size": 399, "state": "file", "uid": 0}

**How to reproduce it?**:
setup docker storage at different partition in /etc/docker/daemon.json
{
"data-root": "**/docker-storage**",
"storage-driver": "overlay2"
}
where docker-storage is a mount point of different partition/LVM. 
/dev/mapper/ubuntu--vg-ubuntu--lv    98G   31G   63G  33% **/**
/dev/mapper/ubuntu--vg-lv--data     504G   56G  423G  12% **/docker-storage**

Configure using typical step: https://microsoft.github.io/superbenchmark/
Will see above error during deploy.

**Log message or shapshot?**:

**Additional information**:

**Comment by abuccts** [comment] 2023-05-10 06:02
Hi, according to the log you shared I think it's some file attribute issues instead of Docker (it hasn't run into Docker yet).

1. Can you check your file system type by `df -hT`? tmpfs does not support file attributes so this Ansible task won't work.
2. If `/` is ext4, can you try reproduce this issue by `ansible-playbook -vvv -i localhost, test.yaml`? Here's the content of test.yaml:

    ```yaml
    - hosts: localhost
      connection: local
      gather_facts: no
      tasks:
      - name: Generating SSH Key Pair
        community.crypto.openssh_keypair:
          path: /home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24/test_id_ed25519
          type: ed25519
          force: no
    ```

**Comment by jdgh000** [comment] 2023-05-10 08:42
here is output:

```
sudo ansible-playbook -vvv test.yaml 
ansible-playbook 2.10.17
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yaml ****************************************************************************************************************************
1 plays in test.yaml

PLAY [localhost] *******************************************************************************************************************************
META: ran handlers

TASK [Generating SSH Key Pair] *****************************************************************************************************************
task path: /home/master/gg/git/superbenchmark/test.yaml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976 `" && echo ansible-tmp-1683708130.5422635-10029-153939200320976="` echo /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/community/crypto/plugins/modules/openssh_keypair.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-100268hh9ne6y/tmpdjttbr1_ TO /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976/AnsiballZ_openssh_keypair.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976/ /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976/AnsiballZ_openssh_keypair.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976/AnsiballZ_openssh_keypair.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1683708130.5422635-10029-153939200320976/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backend": "auto",
            "comment": null,
            "force": false,
            "group": null,
            "mode": null,
            "owner": null,
            "passphrase": null,
            "path": "/home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24/test_id_ed25519",
            "private_key_format": "auto",
            "regenerate": "partial_idempotence",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "size": null,
            "state": "present",
            "type": "ed25519",
            "unsafe_writes": false
        }
    },
    "msg": "The directory /home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24 does not exist or the file is not a directory",
    "name": "/home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24"
}

PLAY RECAP *************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```

**Comment by abuccts** [comment] 2023-05-10 10:31
> "msg": "The directory /home/master/gg/git/superbenchmark/outputs/2023-05-09_16-12-24 does not exist or the file is not a directory",

I got this path from your previous log, not sure why it does not exist. You can also just try `/home/master/gg/git/superbenchmark/`.

**Comment by jdgh000** [comment] 2023-05-10 16:51
I was not sure what to do with this one?
/home/master/gg/git/superbenchmark/.

**Comment by abuccts** [comment] 2023-05-11 06:14
Change the path in yaml to an existing one and retry:
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Generating SSH Key Pair
    community.crypto.openssh_keypair:
      path: /home/master/gg/git/superbenchmark/ # change to an existing path
      type: ed25519
      force: no
```

**Comment by jdgh000** [comment] 2023-05-11 16:57
Now I am getting error which says it is a directory not  a file. I decided to specify dummy file named file1 in that directory and it still errors out (2nd log below) however I do see some ssh key content in file1:

```
(venv) master@system180:~/gg/git/superbenchmark$ sudo ansible-playbook -vvv -i localhost, test.yaml
ansible-playbook 2.10.17
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
No config file found; using defaults
Parsed localhost, inventory source with host_list plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yaml ********************************************************************************************
1 plays in test.yaml

PLAY [localhost] ***********************************************************************************************
META: ran handlers

TASK [Generating SSH Key Pair] *********************************************************************************
task path: /home/nonroot/gg/git/superbenchmark/test.yaml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269 `" && echo ansible-tmp-1683823899.220575-93372-155064795988269="` echo /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/community/crypto/plugins/modules/openssh_keypair.py
<localhost> PUT /root/.ansible/tmp/ansible-local-93369jho5cmcv/tmpqt0ane6d TO /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269/AnsiballZ_openssh_keypair.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269/ /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269/AnsiballZ_openssh_keypair.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269/AnsiballZ_openssh_keypair.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1683823899.220575-93372-155064795988269/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Distribution ubuntu 22.04 on host localhost should use /usr/bin/python3, but is using 
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default 
to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backend": "auto",
            "comment": null,
            "force": false,
            "group": null,
            "mode": null,
            "owner": null,
            "passphrase": null,
            "path": "/home/nonroot/gg/git/superbenchmark/",
            "private_key_format": "auto",
            "regenerate": "partial_idempotence",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "size": null,
            "state": "present",
            "type": "ed25519",
            "unsafe_writes": false
        }
    },
    "msg": "/home/nonroot/gg/git/superbenchmark/ is a directory. Please specify a path to a file."
}

```

```
cat test.yaml | grep path
path: /home/master/gg/git/superbenchmark/file1

sudo ansible-playbook -vvv -i localhost, test.yaml
ansible-playbook 2.10.17
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
No config file found; using defaults
Parsed localhost, inventory source with host_list plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yaml ********************************************************************************************
1 plays in test.yaml

PLAY [localhost] ***********************************************************************************************
META: ran handlers

TASK [Generating SSH Key Pair] *********************************************************************************
task path: /home/nonroot/gg/git/superbenchmark/test.yaml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166 `" && echo ansible-tmp-1683823990.5927923-93525-18296135157166="` echo /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/community/crypto/plugins/modules/openssh_keypair.py
<localhost> PUT /root/.ansible/tmp/ansible-local-935229zyidqia/tmphf0hxu9m TO /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166/AnsiballZ_openssh_keypair.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166/ /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166/AnsiballZ_openssh_keypair.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166/AnsiballZ_openssh_keypair.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1683823990.5927923-93525-18296135157166/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.crypto.openssh_keypair_payload_io996ba5/ansible_community.crypto.openssh_keypair_payload.zip/ansible/module_utils/basic.py", line 1257, in set_attributes_if_different
    raise Exception("Error while setting attributes: %s" % (out + err))
Exception: Error while setting attributes: /home/nonroot/gg/git/superbenchmark/file1: Invalid argument

[DEPRECATION WARNING]: Distribution ubuntu 22.04 on host localhost should use /usr/bin/python3, but is using 
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default 
to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. 
This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "details": "Error while setting attributes: /home/nonroot/gg/git/superbenchmark/file1: Invalid argument\n",
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backend": "auto",
            "comment": null,
            "force": false,
            "group": null,
            "mode": null,
            "owner": null,
            "passphrase": null,
            "path": "/home/nonroot/gg/git/superbenchmark/file1",
            "private_key_format": "auto",
            "regenerate": "partial_idempotence",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "size": null,
            "state": "present",
            "type": "ed25519",
            "unsafe_writes": false
        }
    },
    "mode": "0600",
    "msg": "chattr failed",
    "owner": "root",
    "path": "/home/nonroot/gg/git/superbenchmark/file1",
    "size": 387,
    "state": "file",
    "uid": 0
}

PLAY RECAP *****************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by jdgh000** [comment] 2023-05-22 19:05
any update?

**Comment by abuccts** [comment] 2023-05-23 10:44
Sorry for the late response.

> It is complaining about some attributes, what should that be?

As I mentioned before, tmpfs does not support file attributes. Because this Ansible task will call `chattr` syscall, it does not work on tmpfs and you can see `"msg": "chattr failed"` in your verbose log.

You can confirm it by `df -hT`, `/home/nonroot/` or `/home/master` is probably tmpfs which does not support `chattr` while `/home` is not.


Here are the workarounds for this Ansible issue:
1. use another file system rather than tmpfs for output dir, like you already tried `/home` and it worked
2. if you have to use tmpfs, create the `id_ed25519` and `id_ed25519.pub` files ahead manually before `sb deploy`
3. you can also run it three times, e.g., use the path `/home/nonroot/gg/git/superbenchmark/file1` and try `sudo ansible-playbook -vvv -i localhost, test.yaml` three times, it will fail in the first two times but succeed in the third time

**Comment by cp5555** [comment] 2023-06-30 15:29
Hi @jdgh000 does it work for you now? If so, I will close this issue.

**Closed** 2023-07-05 07:31 UTC
